# Generated by Django 4.2 on 2026-03-27 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('cart_adds_count', models.PositiveIntegerField(default=0)),
                ('purchases_count', models.PositiveIntegerField(default=0)),
                ('wishlist_adds_count', models.PositiveIntegerField(default=0)),
                ('view_to_cart_rate', models.FloatField(default=0.0)),
                ('cart_to_purchase_rate', models.FloatField(default=0.0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_purchased_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('events_count', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('unique_sessions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-hour'],
                'unique_together': {('hour', 'event_type', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('event_type', models.CharField(choices=[('view', 'Просмотр'), ('cart', 'Добавление в корзину'), ('purchase', 'Покупка'), ('search', 'Поиск'), ('wishlist', 'Избранное'), ('review', 'Отзыв'), ('logout', 'Выход'), ('registration', 'Регистрация')], db_index=True, max_length=20)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('search_query', models.CharField(blank=True, max_length=500, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='main.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('events_count', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('unique_sessions', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'event_type', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ReportSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('top_products', 'Топ товаров'), ('conversion', 'Конверсия'), ('sales', 'Продажи'), ('user_activity', 'Активность пользователей')], max_length=50)),
                ('schedule', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'report_type', 'schedule')},
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_ef40a5_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'created_at'], name='analytics_e_user_id_9a87e5_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['session_key', 'created_at'], name='analytics_e_session_64480b_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'created_at'], name='analytics_e_categor_e8aea1_idx'),
        ),
    ]
