# Generated by Django 5.2.7 on 2026-02-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Например: rings, tees, hoodies', unique=True, verbose_name='URL-слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('slug', models.SlugField(help_text='Например: lunar-signet-ring', unique=True, verbose_name='URL-слаг')),
                ('description', models.TextField(help_text='Полное описание для страницы товара', verbose_name='Описание товара')),
                ('short_description', models.CharField(blank=True, help_text='Для превью в каталоге', max_length=300, verbose_name='Краткое описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Сколько штук доступно для покупки', verbose_name='Количество на складе')),
                ('symbol', models.CharField(blank=True, default='◈', help_text='Эмодзи или символ для отображения (☾, ✖, ▲, †, ⛓)', max_length=10, verbose_name='Символ/Иконка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение товара')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен для покупки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='main_produc_created_4330ad_idx'), models.Index(fields=['category', 'available'], name='main_produc_categor_f3ed79_idx')],
            },
        ),
    ]
